### ISSUE TITLE
Git tags missing

### ISSUE THREAD

**Issue by glensc** [spapas/python-git-info#12]
`0 tags`

can you create tags, so could know are there any changes since last release, or compare changes between releases.

if you want i may try to figure out hashes of the releases if you are willing to create the tags.

**Comment by spapas** [comment]
If you can provide a PR with the tags I'll be happy to merge it!

**Comment by glensc** [comment]
I can't provide PR with tags. come on, you write git low level parser and don't know that? :)

I can provide you git hashes where to create tags at, or repo where you can pull in tags and push to your repo.

**Comment by spapas** [comment]
I don't use git tags that much, I don't like them :) 

If you can provide the hashes I can add the tags to them!

**Comment by glensc** [comment]
Are you interested of automating the release process via git tags. i.e if you push package is built and uploaded to pip?

something like this:
- https://github.com/moogar0880/PyTrakt/pull/179

**Comment by glensc** [comment]
you should be able to obtain tags:
- `git fetch https://github.com/glensc/python-git-info`
- `git push --tags`

**Comment by spapas** [comment]
Thanks I've merged the tags https://github.com/spapas/python-git-info/tags. 

The gh action is also interesting to me but I'll need to test it a bit more before integrating it!

Thanks again!

**Comment by glensc** [comment]
The release automation via git tags push is basically:
1. use this as base: https://github.com/moogar0880/PyTrakt/pull/179/files
2. figure out how modify setup.py to take version from environment
3. update workflow to set version from git tag
4. don't forget to generate pip token and setup to github actions secret

**Comment by spapas** [comment]
This must be ok now; thanks for the help

**Comment by glensc** [comment]
also, if you plan develop that automation yourself, I suggest to use branch so you can add tons of noisy commits, but later squash them to a single commit.

here's another publishing flow that setups the version for build to use:
- https://github.com/Taxel/PlexTraktSync/blob/0.20.4/.github/workflows/pypi.yml

**Comment by spapas** [comment]
Thanks! This is a little too complex for my tastes :) Everything needs time to integrate with my project and test and unfortunately I have little spare time :( I'd be happy to merge a PR that works though!

**Comment by glensc** [comment]
that's why i asked do you want me to submit the pr

**Comment by glensc** [comment]
You can't mix github releases and git tags, if you use releases you must use them for all tags. otherwise the "latest" will be pointing to a release, not a tag:
- https://github.com/spapas/python-git-info/releases

you should just delete these two releases:
- https://github.com/spapas/python-git-info/releases/tag/0.7.5
- https://github.com/spapas/python-git-info/releases/tag/0.7.4

**Comment by spapas** [comment]
I deleted the releases instead, is it ok now ?

**Comment by glensc** [comment]
yes, it doesn't show now 0.7.5 as "latest" anymore
