### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by glensc** [spapas/python-git-info#14]
Source:
- https://github.com/Taxel/PlexTraktSync/runs/7451538136?check_suite_focus=true

refs:
- https://github.com/Taxel/PlexTraktSync/pull/981#issuecomment-1191561821

**Comment by spapas** [comment]
Ah sorry this definitely is related to the commit adding the feature for this https://github.com/spapas/python-git-info/issues/13... 

I'll fix it in a little thanks for reporting!

**Comment by spapas** [comment]
@glensc can you try with version 0.7.6 ?

**Comment by glensc** [comment]
CI passed:
- https://github.com/Taxel/PlexTraktSync/pull/983

so, probably ok
