### ISSUE TITLE
only one pack supported?

### ISSUE THREAD

**Issue by glensc** [spapas/python-git-info#6]
- https://github.com/spapas/python-git-info/blob/42c5642f44412540a5568a78c4c6e0089592ff80/gitinfo/gitinfo.py#L65-L69

this can't be right, what if the result is not in the first pack?

```
➔ ls .git/objects/pack/ -1
pack-0ec15a5c455b073ecd17117d2e532912ffd92718.idx
pack-0ec15a5c455b073ecd17117d2e532912ffd92718.pack
pack-187f6797dc3ecb60b02c39bfa6eae609d0ef3a0e.idx
pack-187f6797dc3ecb60b02c39bfa6eae609d0ef3a0e.pack
pack-d4a73e4189acceb1402f49cde1bcfc72601fb1c3.idx
pack-d4a73e4189acceb1402f49cde1bcfc72601fb1c3.pack
pack-fa81fcae803551f069e6e95fdd552bf46dd08b04.idx
pack-fa81fcae803551f069e6e95fdd552bf46dd08b04.pack
```

**Comment by spapas** [comment]
Hello thank you for reporting the problem! Is there an example where the library breaks so I can debug it?

**Comment by glensc** [comment]
@spapas no. I just looked at the code.

**Comment by glensc** [comment]
I was actually looking for something simple that can do `git describe --tags`, but this will do as well.

**Comment by glensc** [comment]
@spapas  I guess you can just copy *.pack, *.idx from any other arbitrary .git dir to test.

**Comment by spapas** [comment]
This should be fixed now.
