### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by glensc** [spapas/python-git-info#7]
```
  File "plex_trakt_sync/commands/sync.py", line 212, in sync
    git_version = git_version_info()
  File "plex_trakt_sync/version.py", line 7, in git_version_info
    commit = get_git_info()
  File "/usr/local/lib/python3.9/site-packages/gitinfo/gitinfo.py", line 90, in get_git_info
    return get_git_info_dir(gitdir)
  File "/usr/local/lib/python3.9/site-packages/gitinfo/gitinfo.py", line 69, in get_git_info_dir
    return get_pack_info(idx_file, gi)
  File "/usr/local/lib/python3.9/site-packages/gitinfo/pack_reader.py", line 67, in get_pack_info
    pack_idx, index_tot_objects = get_pack_idx(idx_file, gi['commit'])
TypeError: cannot unpack non-iterable NoneType object
```

please add catch `TypeError` and return `None`!

**Comment by spapas** [comment]
Hello could you please provide a git repo that throws this error so I can properly debug it ?

**Comment by glensc** [comment]
@spapas no I can't. it went away after the next commit. and I don't want to, it's my private doings.

you should be able to add a guard based on exception trace to return None rather crashing application with an uncaught exception.

**Comment by spapas** [comment]
It's all right... I've found out that there are more things missing from this project for exampe it doesn't work if the latest commit is of type `OBJ_OFS_DELTA` (it only works if it's `OBJ_COMMIT`). I'll try to research the git internals on how to parse the `OBJ_OFS_DELTA` and see if this also helps with that.

**Comment by spapas** [comment]
This error should be fixed now!
