### ISSUE TITLE
Question about whether we can decode deltas without idx file

### ISSUE THREAD

**Issue by reven33** [spapas/python-git-info#8]
Hi,

I am working on an interceptor to intercept the git push payload which is a .pack format file for security validations. I can follow the git pack format https://git-scm.com/docs/pack-format to get undeltified objects like commit but not for OBJ_OFS_DELTA and OBJ_REF_DELTA. Does anyone know how to decode deltas and get the actual diffs from the git push payload? If there is not a way to decode deltas without idk file, can i get the actual length of deltas?

Really appreciate for any help

Regards

**Comment by piano-antinomy** [comment]
+1

**Comment by spapas** [comment]
Hello unfortunately I am not very experienced with the git format to be able to answer this question properly :| 

I am struggling to decode OBJ_OFS_DELTA objects right now normally :)

I recommend trying either the #git freenode irc channel or maybe the git developers mailing list.

**Comment by spapas** [comment]
Closing because this is not a real issue but a question.
