### ISSUE TITLE
Newlines not present in commit['message']

### ISSUE THREAD

**Issue by glensc** [spapas/python-git-info#9]
```
INFO: PlexTraktSync [203b3b74: Revert "Lower log noise from requests_cache"This reverts commit b9abe807d0f64c1dd650fc1243795e76ba825c33. @2021-04-25 17:58:47]
```

The code to print that is following:
- https://github.com/Taxel/PlexTraktSync/blob/75dc59ef463f678cb48998ac372582bb2c0f9935/plex_trakt_sync/commands/sync.py#L178-L180

which is just a smaller wrapper:
- https://github.com/Taxel/PlexTraktSync/blob/75dc59ef463f678cb48998ac372582bb2c0f9935/plex_trakt_sync/version.py#L1-L11

however, the actual commit message has `\n\n` between `title` and `body`:

```
 ➔ git show
commit 203b3b74e6bbea6c884424267761e54a70459248 (HEAD -> requests-cache-0.6.x)
Author: Elan Ruusamäe <glen@pld-linux.org>
Date:   Sun Apr 25 17:58:47 2021 +0300

    Revert "Lower log noise from requests_cache"

    This reverts commit b9abe807d0f64c1dd650fc1243795e76ba825c33.

diff --git a/plex_trakt_sync/logging.py b/plex_trakt_sync/logging.py
```

I didn't look closely, maybe newlines are `\0`, but I guess they're just lost:

```
➔ python3 -c "print('a\x00b')"
ab
```

**Comment by spapas** [comment]
Thank you for reporting. Fixed in new version 0.7.1.

**Comment by glensc** [comment]
@spapas please add cross links too, easier to find the fix.

**Comment by glensc** [comment]
@spapas by cross-links I mean if you didn't refer to issue in pull request or in commit message, lav commit id as a comment.

seems this was fixed in https://github.com/spapas/python-git-info/commit/2e71a95ce5d5dab97320eb32696b4fdd8f7e4cf0, but I may be mistaken of course.
